version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - ./database/sql-scripts:/home
    container_name: database
    healthcheck:
      test: bash -c 'mysql --user="root" --database="jet_store_db" --password="123456"  < "/home/CreateTable.sql"'
      interval: 20s
      timeout: 30s
      retries: 500
  backend:
    depends_on:
      mysqldb:
        condition: service_healthy
    build: ./backend
    restart: always
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT_BACKEND:$NODE_DOCKER_PORT_BACKEND
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - MYSQLDB_HOST=$MYSQLDB_HOST
    stdin_open: true
    tty: true
    container_name: backend
  frontend:
    depends_on:
      - backend
    build: ./frontend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT_FRONTEND:80
    stdin_open: true
    tty: true
    container_name: frontend
