version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - ./database/db:/var/lib/mysql
      - ./database/sql-scripts:/home
    container_name: database
  backend:
    depends_on:
      - mysqldb
    build: ./backend
    volumes:
      - ./backend:/backend/
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT_BACKEND:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
    container_name: backend
  frontend-dev:
    depends_on:
      - backend
    build: 
     context: ./frontend
     dockerfile: Dockerfile-dev
    volumes:
      - ./frontend:/frontend/
    restart: unless-stopped
    stdin_open: true
    tty: true
    container_name: frontend-dev
    # healthcheck:
    #   test: bash -c "[ -f /frontend/dist/frontend/index.html ]"
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
  frontend:
    depends_on:
      - frontend-dev
      # frontend-dev:
      #   condition: service_healthy
    build: ./frontend
    ports:
      - 80:80
    volumes:
      - ./frontend/html:/usr/share/nginx/html/
    container_name: frontend
    restart: always
    
    # docker exec -it database  bash -c 'mysql --user="root" --database="bezkoder_db" --password="123456"  < "/home/CreateTable.sql"'
    # docker exec -it database  bash -c 'mysql --user="root" --database="bezkoder_db" --password="123456"  < "/home/InsertInto.sql"'